#!/usr/bin/env bash

action=$1
shift
mode=$1

function usage {
	echo "  $(basename $0) [-v]"
	echo "    Record all changes in Git repository located at $TODO_DIR."
	echo "    If -v argument is provided, only a preview will be shown."
	echo ""
	exit
}

[ "$action" = "usage" ] && usage

$TODO_FULL_SH archive

cd "$TODO_DIR"
git diff
if [ "$mode" != "-v" ]; then
	git commit -a $mode --allow-empty-message -m ""
fi
