#!/usr/bin/env bash

action=$1

function usage {
	echo "  $(basename $0)"
	echo "    Pull changes into git repository located at $TODO_DIR."
	echo "    Always pulls from origin/master into local master branch."
	echo ""
	exit
}

[ "$action" = "usage" ] && usage

cd "$TODO_DIR"
git fetch origin
git merge origin/master
