#!/usr/bin/env bash

action=$1

function usage {
	echo "  $(basename $0)"
        echo "  Uses the commit, pull and push addons to keep the local "
        echo "  repository at $TODO_DIR and remote repository in sync. "
	echo ""
	exit
}

[ "$action" = "usage" ] && usage

$TODO_FULL_SH commit
$TODO_FULL_SH pull
$TODO_FULL_SH push
