#!/bin/bash

NPROC=$(nproc)

if [ ! -n "$NPROC" ]; then
    NPROC=4
fi

ISBUILD=$(basename $(pwd))

if [[ "$ISBUILD" == "build" ]]; then
    echo "Already in build directory";
    BUILDIR=$(pwd)
else
    mkdir -p $BUILDIR
    BUILDIR=$(pwd)/build
fi

## Build using cmake.
if [[ $1 == "--clean" ]]; then
    echo "Cleaning old cmake cache files"
    find . -name "*CMakeCache*" -print0 | xargs -I file rm -f file
    exit
else
    echo "Warning: Using old CMakeCache files."
fi


GITTAG=$(git rev-parse --short HEAD)
(
    cd $BUILDIR
    set -e
    cmake -DCMAKE_INSTALL_PREFIX=/tmp/$GITTAG .. "$@"
    make -j$NPROC | tee __$GITTAG__.log
    ctest --output-on-failure --rerun-failed
    make install
    set +e
)
