#!/bin/sh

#
# Lintian from debian:unstable maintained by https://github.com/eddelbuettel/docker-lintian
#
podman run \
    -w /root \
    -v ${PWD}:/root/ \
    --user ${UID}:${GID} \
    -it eddelbuettel/lintian \
    lintian $@
