#!/usr/bin/env python3
# -*- coding: utf-8 -*-

__author__ = "Dilawar Singh"
__email__ = "dilawar@subcom.tech"

import os
from pathlib import Path

import typer
app = typer.Typer()

CACHE_DIR_ = Path(os.environ['HOME']) / '.cache' / 'iprm'
CACHE_DIR_.mkdir(parents=True, exist_ok=True)

def __show_trash(glob : str = '**'):
    for f in Path(CACHE_DIR_).glob(glob):
        print(f)

@app.command()
def main(path : Path = Path('.'), show_trash:bool=False):
    if path.exists():
        path.rename(CACHE_DIR_ / path)
        return

    if show_trash:
        __show_trash(path)
    raise RuntimeWarning(f'{path} does not exists')


if __name__ == '__main__':
    app()
