#!/bin/sh

set -e
JARFILE=$HOME/Scripts/bfg-1.13.0.jar
URL=https://repo1.maven.org/maven2/com/madgag/bfg/1.13.0/bfg-1.13.0.jar
if [ ! -f $JARFILE ]; then
    echo "Downloading jar file"
    wget $URL -O $JARFILE
fi

set -x
java -jar $HOME/Scripts/bfg-1.13.0.jar $@
