#!/bin/bash -
#===============================================================================
#
#          FILE: docker_ncbs.sh
#
#         USAGE: ./docker_ncbs.sh
#
#   DESCRIPTION:  Docker inside NCBS.
#
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Dilawar Singh (), dilawars@ncbs.res.in
#  ORGANIZATION: NCBS Bangalore
#       CREATED: Saturday 03 February 2018 01:15:40  IST
#      REVISION:  ---
#===============================================================================

set -o nounset                                  # Treat unset variables as an error

docker build --build-arg "https_proxy=http://proxy.ncbs.res.in:3128" \
    --build-arg "http_proxy=http://proxy.ncbs.res.in:3128" \
    "$@"
