#!/usr/bin/env python

from graph_tool.all import load_graph, graph_draw
import sys

if len(sys.argv) < 1 :
  print "usage : viewgraphml filename"
  sys.exit()

G = load_graph(sys.argv[1], 'xml')
if len(sys.argv) < 3 :
  graph_draw(G)
