#!/usr/bin/env bash
set -e
PWD=$(pwd)
docker run --workdir /obs \
  --mount type=bind,source=$PWD,target=/obs \
  -v /var/tmp:/var/tmp:rw \
  -v $HOME/.config/osc/:/root/.config/osc:rw \
  -it dilawars/obs \
  osc "$@"

