#!/usr/bin/env fish

set -e
set -x

PORT=8123

if [[ ! -v PGADMIN_DEFAULT_PASSWORD ]]; then
    echo "You must set PGADMIN_DEFAULT_PASSWORD";
    exit 1;
fi

docker pull dpage/pgadmin4
docker run -p $PORT:80 \
    -e 'PGADMIN_DEFAULT_EMAIL=dilawar.s.rajput@gmail.com' \
    -d dpage/pgadmin4

echo "[INFO] Running on port $PORT..."
