#!/usr/bin/env bash

set -e
set -x

PORT=8123

docker pull dpage/pgadmin4
docker run -p $PORT:80 \
    -e 'PGADMIN_DEFAULT_EMAIL=user@domain.com' \
    -e 'PGADMIN_DEFAULT_PASSWORD=SuperSecret' \
    -d dpage/pgadmin4

echo "[INFO] Running on port $PORT..."
