#!/bin/bash

# This script launches an application in terminal silently
# set -x

COMMAND=$1
if which $COMMAND > /dev/null; then
    "$@" &> /dev/null | tee /tmp/"$1.log" &
else
    echo "Could not locate $COMMAND"
    exit 1;
fi
