newline_style = "unix"
use_field_init_shorthand = true
use_try_shorthand = true

indent_style = "Block"
group_imports = "StdExternalCrate"
# report_todo = "Always"
# report_fixme = "Always"
unstable_features = true
format_strings = true
imports_granularity = "Module"
wrap_comments = true
