#!/bin/bash
# This script search for files in linux.
#
# It searches in two mode. Filename mode and pattern mode. if no pattern to
# search inside file is given then it searches only for name.

function formatPath
{
    local dir=''
    local pat=''

    echo "$dir $pat"
}


if [ $@ -eq 2 ]; then
    search_for_text=True
    txt=$2
elif [[ $@ -lt 1 ]] || [[ $@ -gt 2 ]]; then
    echo "Usage: $0 path_pattern [text_pattern]"
fi
file_pat=$1


formatter_pat=$(formatPath $file_pat)

