#!/bin/bash
set -e

CONFIGDIR=$HOME/.config/tldr
mkdir -p $CONFIGDIR

OS=common
BASE_URL=https://raw.githubusercontent.com/tldr-pages/tldr/master/pages
QUERY=$1

if [[ ! -z "$QUERY" ]]; then
    PAGE=`curl $BASE_URL/$OS/$QUERY.md`
    if [[ -z $PAGE ]]; then
        OS=linux
        PAGE=`curl $BASE_URL/$OS/$QUERY.md`
    fi

fi

mdv $PAGE
