#!/usr/bin/env bash

set -e

CONFIGDIR=$HOME/.config/tldr
mkdir -p $CONFIGDIR

OS=common
BASE_URL=https://raw.githubusercontent.com/tldr-pages/tldr/master/pages
QUERY=$1

function download
{
    wget $BASE_URL/$OS/$1 -o $CONFIGDIR/$1
}

FILENAME=$QUERY.md
if [[ ! -z "$QUERY" ]]; then
    if [[ ! -f $CONFIGDIR/$FILENAME ]]; then
        download $BASE_URL/$OS/$FILENAME
        if [[ ! -f $CONFIGDIR/$FILENAME ]]; then
            OS=linux
            download $BASE_URL/$OS/$FILENAME
        fi
    fi

fi

mdv $CONFIGDIR/$FILENAME
