#!/usr/bin/env bash

set -e

CONFIGDIR=$HOME/.config/tldr
mkdir -p $CONFIGDIR

OS=common
BASE_URL=https://raw.githubusercontent.com/tldr-pages/tldr/master/pages
QUERY=$1

function download_tldr
{
    URL=$BASE_URL/$OS/$1
    curl -s $URL -o $CONFIGDIR/$1
}

FILENAME=$QUERY.md
if [[ ! -z "$QUERY" ]]; then
    if [[ ! -f $CONFIGDIR/$FILENAME ]]; then
        download_tldr $FILENAME
        if [[ ! -f $CONFIGDIR/$FILENAME ]]; then
            OS=linux
            download_tldr $FILENAME
        fi
    fi

fi

pandoc $CONFIGDIR/$FILENAME | lynx -stdin
