#!/usr/bin/env python
import networkx as nx
import matplotlib.pyplot as plt
import sys

if len(sys.argv) < 1 :
  print "usage : viewgraphml filename"
  sys.exit()

G = nx.read_graphml(sys.argv[1])
if len(sys.argv) < 3 :
  nx.draw(G)
elif sys.argv[2] == 's' :
  nx.draw_spectral(g)
elif sys.argv[2] == 'r' :
  nx.draw_random(G)
elif sys.argv[2] == 'c' :
  nx.draw_circular(G)
plt.show()
