#!/usr/bin/env python

import sys
import re
import subprocess
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.style.use( 'bmh' )

def parse( output ):
    try:
        output = output.decode( 'utf-8' )
    except Exception as e:
        pass
    print( output )
    variables = re.findall( r'\d+\:d(?P<id>\S+?)/dt=', output )
    return variables

def main(  ):
    infile = sys.argv[1]
    print( '[INFO] Solving system in file %s' % infile )
    cmd = 'xppaut -silent %s %s' % (''.join(sys.argv[2:]), infile)
    print( '   Executing %s' % cmd )
    res = subprocess.check_output( cmd.split( ), shell=False )
    variables = parse( res ) 
    print( '[INFO] Plotting' )
    data = np.loadtxt( 'output.dat' )
    tvec = data[:,0]
    for i, k in enumerate( variables ):
        ax = plt.subplot( len(variables), 1, i + 1 )
        ax.plot( tvec, data[:,i+1], label = k )
        ax.legend( )
    outfile = '%s.png' % infile
    plt.savefig( outfile )
    print( 'Saved to %s' % outfile )

if __name__ == '__main__':
    main( )
