# Thanks https://www.reddit.com/r/firefox/comments/1dzybke/comment/lpp69ix/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
solve: ./50-fixup-apple-color-emoji.conf 
	cp ./50-fixup-apple-color-emoji.conf ~/.config/fontconfig/conf.d/
